version: 2.1
orbs:
  # Your orb will be automatically injected here during the pipeline.
  # Reference your orb's jobs and commands below as they will exist when built.
  orb-tools: circleci/orb-tools@12.3
  # The orb definition is intentionally not included here. It will be injected into the pipeline.
  circleci-ms-teams: {}

# Use this tag to ensure test jobs always run,
# even though the downstream publish job will only run on release tags.
filters: &filters
  tags:
    only: /.*/

# Filter for release tags.
release-filters: &release-filters
  branches:
    ignore: /.*/
  tags:
    only: /^v[0-9]+\.[0-9]+\.[0-9]+$/

jobs:
  command-notify:
    parameters:
      only_on_fail:
        type: boolean
        default: false
    docker:
      - image: cimg/base:edge
    steps:
      - checkout
      # Run your orb's commands to validate them.
      - run:
          when: always
          name: Export WEBHOOK variable
          command: |
            echo 'export WEBHOOK="${PARAM_WEBHOOK:-${TEAMS_WEBHOOK:-${TEAMS_WEBHOOK_ORG}}}"' >> $BASH_ENV
      - circleci-ms-teams/status:
          fail_only: << parameters.only_on_fail >>

workflows:
  test-deploy:
    jobs:
      - command-notify:
          name: command-notify/test
          only_on_fail: true
          context: default
          filters: *filters
      # The orb must be re-packed for publishing, and saved to the workspace.
      - orb-tools/pack:
          filters: *release-filters
      - orb-tools/publish:
          orb_name: simpleviewinc/circleci-ms-teams
          vcs_type: << pipeline.project.type >>
          pub_type: production
          # Ensure this job requires all test jobs and the pack job.
          requires:
            - orb-tools/pack
          context: orb-publishing
          filters: *release-filters
      - command-notify:
          name: command-notify/complete
          context: default
          filters: *filters
          requires:
            - command-notify/test
            - orb-tools/publish
